name: Code Coverage
on:
  push: # On every push on any branch
jobs:
  Coverage: # Job name
    runs-on:
      ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v3.1.0
        with:
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)