name: github-release

on:
  workflow_run:
    workflows:
      - code-coverage
    types:
      - completed
    branches:
      - main
env:
  PROJECT_NAME: ci-test
  WORKFLOW: github-release
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Create Artifact
        run: sbt assembly

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: release
          path: target/scala-3.2.0-RC1/ci-test-assembly-0.1.0-SNAPSHOT.jar

  github-release:
    name: Create GitHub Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: release
          path: target/scala-3.2.0-RC1/ci-test-assembly-0.1.0-SNAPSHOT.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: target/scala-3.2.0-RC1/ci-test-assembly-0.1.0-SNAPSHOT.jar