name: Create Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Generate JAR"
        run: sbt assembly
      - name: "Upload a Build Artifact"
        uses: actions/upload-artifact@v3.1.0
        with:
          name: "ci-test"
          path: ./target/scala-3.1.3/ci-test-assembly-0.1.0-SNAPSHOT.jar
      retention-days: 0