name: Scala CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Coverage Report
          run: sbt jacoco
        - name: "Upload coverage to Codecov"
          uses: "codecov/codecov-action@v2"
          with:
            fail_ci_if_error: true