name: Run Tests

on:
  push:
    branches:
      - develop
      - main

    pull_request:
      types: [ opened, synchronize, reopened ]

jobs:
  code-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Run tests
        run: sbt test
